version: '3'

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 127.0.0.1/16

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "5501:5501"
    networks:
      my_network:
        ipv4_address: 127.0.0.1  # Define the static IP address for the app service

  cypress:
    image: cypress/included:latest
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://127.0.0.1:5501  # Update the baseUrl to use the static IP address
    networks:
      - my_network
